export const MODAL_SET = 'MODAL_SET';
export const MODAL_HIDE = 'MODAL_HIDE';
export const MODAL_SHOW = 'MODAL_SHOW';
export const MODAL_TOGGLE = 'MODAL_TOGGLE';

export const USER_FETCH_REGISTER = 'USER_FETCH_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';
export const USER_FETCH_REGISTER_BY_EMAIL = 'USER_FETCH_REGISTER_BY_EMAIL';
export const USER_REGISTER_ERROR_BY_EMAIL = 'USER_REGISTER_ERROR_BY_EMAIL';
export const USER_REGISTER_SUCCESS_BY_EMAIL = 'USER_REGISTER_SUCCESS_BY_EMAIL';
export const USER_FETCH_LOGIN = 'USER_FETCH_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_READY = 'USER_READY';

export const SET_POPUP = 'SET_POPUP';
export const SET_PROFILE = 'SET_PROFILE';
export const SET_PRIVATE = 'SET_PRIVATE';
export const SET_PRIVATE_ID = 'SET_PRIVATE_ID';
export const SET_CATS = 'SET_CATS';
export const HIDE_MORE = 'HIDE_MORE';

export const SET_PAY_PENDING = 'SET_PAY_PENDING';
export const SET_PAY_SUCCESS = 'SET_PAY_SUCCESS';
export const SET_SUB_PENDING = 'SET_SUB_PENDING';
export const SET_SUB_SUCCESS = 'SET_SUB_SUCCESS';
export const SET_DIS_PENDING = 'SET_DIS_PENDING';
export const SET_DIS_SUCCESS = 'SET_DIS_SUCCESS';

export const TASK = {
    REQUEST: 'TASK.REQUEST',
    SUCCESS: 'TASK.SUCCESS',
    FAILURE: 'TASK.FAILURE',
}

export const TASKS = {
    REQUEST: 'TASKS.REQUEST',
    SUCCESS: 'TASKS.SUCCESS',
    FAILURE: 'TASKS.FAILURE',
}

export const STORIES = {
    REQUEST: 'STORIES.REQUEST',
    SUCCESS: 'STORIES.SUCCESS',
    FAILURE: 'STORIES.FAILURE',
}

export const WITHDRAWAL = {
    REQUEST: 'WITHDRAWAL.REQUEST',
    SUCCESS: 'WITHDRAWAL.SUCCESS',
    FAILURE: 'WITHDRAWAL.FAILURE',
}

export const PASSWORD = {
    REQUEST: 'PASSWORD.REQUEST',
    SUCCESS: 'PASSWORD.SUCCESS',
}

export const INFO = {
    REQUEST: 'INFO.REQUEST',
    SUCCESS: 'INFO.SUCCESS',
}

export const SET_JIVO_SHOW = 'SET_JIVO_SHOW';